
---
- name: Add kdenlive repository
  become: true
  apt_repository:
    repo: 'ppa:kdenlive/kdenlive-stable'

- name: Install all apps
  become: true
  apt:
    update_cache: true
    pkg:
      - imagemagick
      - kdenlive
      - simplescreenrecorder
      - krita
      - audacity
    state: latest