Vagrant.configure(2) do |config|
        config.vm.box = "ubuntu/groovy64"
        config.vm.hostname = "test-machine"
        config.vm.box_check_update = false
        config.vm.synced_folder ".", "/vagrant", disabled: true

        config.vm.provider "virtualbox" do |v|
                v.memory = 512
                v.cpus = 1
        end

        config.vm.provision "ansible" do |ansible|
                ansible.playbook = "../playbook-test.yml"
                ansible.config_file = "../ansible.cfg"
        end
end
