- name: Install all apps
  become: true
  apt:
    update_cache: yes 
    pkg:
      - neovim  
    state: latest

- name: Install vim-plug
  shell: curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  register: debUrl
  args:
    warn: False

- name: Create a symbolic link
  file:
    src:  ~/.dotfiles/nvim/init.vim
    dest: ~/.config/nvim/init.vim
    state: link
